#!/usr/bin/env python3

import threading
import webbrowser

import uvicorn


def open_browser() -> None:
    """
    Opens the SentinelIR web interface in the user's default browser.
    """
    webbrowser.open("http://127.0.0.1:8000/")


def main() -> None:
    """
    Starts the SentinelIR FastAPI web application and opens the browser.
    """
    threading.Timer(1.0, open_browser).start()

    uvicorn.run(
        "app.api.main:app",
        host="127.0.0.1",
        port=8000,
        reload=True
    )


if __name__ == "__main__":
    main()
